chore: bump rust toolchain to fix broken CI (#296)
Fixes the broken backend-rust-canbench.yml CI workflow, which currently
[fails](https://github.com/dfinity/vetkeys/actions/runs/21644361526/job/62392399166)
with
```
error: failed to compile `canbench v0.4.0` [...]

Caused by:
  rustc 1.85.0 is not supported by the following packages:
    time@0.3.46 requires rustc 1.88.0
    time-core@0.1.8 requires rustc 1.88.0
```